apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ui:
      color: "#1d3557"
      message: "Hello from staging!"
